In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.core.interactiveshell import InteractiveShell 
InteractiveShell.ast_node_interactivity = "all"

In [16]:
def default(c):
    amin = c.min(axis=1)
    bmax = c.max(axis=0)
    alpha = max(amin)
    beta = min(bmax)
    print(f'Нижняя цена игры: {alpha}')
    print(f'Верхняя цена игры: {beta}')
    print(f'Седловая точка существует') if alpha == beta else print(f'Седловая точка не существует')
    if alpha == beta:
        print(f'Координаты седловой точки равны ({np.argmax(amin)+1}, {np.argmin(bmax)+1})')
    p1 = (c[1,1]-c[1,0])/(c[0,0]+c[1,1]-(c[0,1]+c[1,0]))
    p2 = 1-p1
    q1 = (c[1,1]-c[0,1])/(c[0,0]+c[1,1]-(c[0,1]+c[1,0]))
    q2 = 1-q1
    v = c[0,0]*p1+c[1,0]*p2
    print(p1,p2,q1,q2,v)

In [26]:
c1 = np.array([[4,8,-1,-2], [5,9,3,2], [5,-7,-2,4]])
c2 = np.array([[5,9],[8,3]])
c3 = np.array([[5,8,6,4,7], [3,2,4,8,9]])
c31 = np.array([[5,4],[3,8]])
c4 = np.array([[-4,2],[5,7],[2,-8],[-1,4],[6,-3]])
c41 = np.array([[5,7],[6,-3]])
c5 = np.array([[2,6,4,5], [7,2,3,1], [5,3,6,2]])
# c1,c2,c3,c4,c5

In [41]:
default(c5)

Нижняя цена игры: 2
Верхняя цена игры: 5
Седловая точка не существует
0.5555555555555556 0.4444444444444444 0.4444444444444444 0.5555555555555556 4.222222222222221


In [40]:
ist = 57/11
schit = 5/1
(np.abs(ist-schit)/ist)*100
(np.abs((1-ist)-(1-schit))/(1-ist))*100

3.5087719298245585

-4.347826086956518

In [44]:
from scipy.optimize import linprog

In [47]:
obj = [1,1,1]
lhs_ineq = [[-2,-7,-5],[-6,-2,-3],[-4,-3,-6], [-5,-1,-2]]  
rhs_ineq = [-1,-1,-1,-1] 
bnd = [(0, float("inf")),(0, float("inf")),(0, float("inf"))] 
opt = linprog(c=obj, A_ub=lhs_ineq, b_ub=rhs_ineq, bounds=bnd,method="simplex")
opt.fun.round(3)
opt.x.round(3)

0.273

array([0.182, 0.091, 0.   ])

In [50]:
(1/opt.fun).round(3)
(1/opt.fun) * opt.x

3.667

array([0.66666667, 0.33333333, 0.        ])

In [54]:
obj = [-1,-1,-1,-1]
lhs_ineq = [[2,6,4,5],[7,2,3,1],[5,3,6,2]]  
rhs_ineq = [1,1,1] 
bnd = [(0, float("inf")),(0, float("inf")),(0, float("inf")), (0, float("inf"))]
opt = linprog(c=obj, A_ub=lhs_ineq, b_ub=rhs_ineq, bounds=bnd,method="simplex")
-opt.fun.round(3)
opt.x.round(3)
(-1/opt.fun).round(3)
(-1/opt.fun) * opt.x

0.273

array([0.111, 0.   , 0.03 , 0.131])

3.667

array([0.40740741, 0.        , 0.11111111, 0.48148148])