In [26]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell 
InteractiveShell.ast_node_interactivity = "all"

In [35]:
mat = np.random.uniform(low=1/11, high=11, size=(10,10)).round(2)
print(mat)                   

[[ 1.39  7.14  3.33  3.67  8.05  8.67  2.69  0.67  9.88  3.15]
 [ 7.26  9.17  7.76 10.94  8.58  3.72  2.93  8.74  0.66  4.14]
 [ 1.02  8.7   7.34  6.31  5.52  2.35  4.86  9.2   9.19  0.29]
 [ 0.72  5.1   5.43  4.47  4.27  9.6   5.87  4.87  0.53  7.03]
 [10.74  8.65  1.34  1.48  2.11  4.79  1.93  4.52  6.09  2.78]
 [ 5.12  4.34  7.4   5.1   2.08  3.13  0.38  5.48  0.72  7.88]
 [ 0.48  9.15  9.74  7.89  3.27  3.2   5.25  8.63  0.53  0.98]
 [ 5.96  8.35  4.46  8.02  9.35  4.23  9.22  7.65  9.03 10.46]
 [ 2.3   5.51  2.48  2.45  7.96  6.63  9.18  8.97  9.97  6.92]
 [ 9.99 10.71  8.7   4.35 10.47  5.55  8.03  0.86  6.38  1.86]]


In [36]:
gamma = 1/12
amin = mat.min(axis=1)
amax = mat.max(axis=1)
coef = gamma*amax + (1-gamma)*amin
alpha = np.max(coef)
strat = np.argmax(coef)+1

In [37]:
f'Коэффициент Гурвица для каждой стратегии - {coef.round(2)}'
f'Максимальный коэффициент = {alpha.round(2)}'
f'Оптимальная стратегия - {strat}'

'Коэффициент Гурвица для каждой стратегии - [1.44 1.52 1.03 1.29 2.12 1.   1.25 4.75 2.94 1.68]'

'Максимальный коэффициент = 4.75'

'Оптимальная стратегия - 8'