In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.core.interactiveshell import InteractiveShell 
InteractiveShell.ast_node_interactivity = "all"

In [37]:
def default(c):
    amin = c.min(axis=1)
    bmax = c.max(axis=0)
    alpha = max(amin)
    beta = min(bmax)
    print(f'Нижняя цена игры равна {alpha}')
    print(f'Верхняя цена игры равна {beta}')
    print(f'Седловая точка существует') if alpha == beta else print(f'Седловая точка не существует')
    if alpha == beta:
        print(f'Координаты седловой точки равны ({np.argmax(amin)+1}, {np.argmin(bmax)+1})')
    p1 = (c[1,1]-c[1,0])/(c[0,0]+c[1,1]-(c[0,1]+c[1,0]))
    p2 = 1-p1
    q1 = (c[1,1]-c[0,1])/(c[0,0]+c[1,1]-(c[0,1]+c[1,0]))
    q2 = 1-q1
    v = c[0,0]*p1+c[1,0]*p2
    print(p1,p2,q1,q2,v)

In [48]:
c1 = np.array([[2,3,-1,4], [3,2,4,1], [-4,3,-1,-2], [-5,5,-3,-4]])
c2 = np.array([[4,1],[2,4]])
c3 = np.array([[0.5,0.3,0.6,0.7,0.8], [0.6,0.5,0.4,0.9,1.1]])
c31 = np.array([[0.3,0.6],[0.5,0.4]])
c4 = np.array([[3,8],[7,6],[4,5],[9,2],[6,1]])
c41 = np.array([[3,8],[7,6]])
c5 = np.array([[4,5,6], [7,3,2], [2,1,8]])

In [50]:
default(c5)

Нижняя цена игры равна 4
Верхняя цена игры равна 5
Седловая точка не существует
0.8 0.19999999999999996 0.4 0.6 4.6


In [57]:
from scipy.optimize import linprog
obj = [1,1,1]
lhs_ineq = [[-4,-7,-2],[-5,-3,-1],[-6,-2,-8]]  
rhs_ineq = [-1,-1,-1] 
bnd = [(0, float("inf")),(0, float("inf")),(0, float("inf"))] 
opt = linprog(c=obj, A_ub=lhs_ineq, b_ub=rhs_ineq, bounds=bnd,method="simplex")
opt.fun.round(3)
opt.x.round(3)
(1/opt.fun) * opt.x
(1/opt.fun).round(3)

0.217

array([0.174, 0.043, 0.   ])

array([0.8, 0.2, 0. ])

4.6

In [63]:
from scipy.optimize import linprog
obj = [-1,-1,-1]
lhs_ineq = [[4,5,6],[7,3,2],[2,1,8]]  
rhs_ineq = [1,1,1] 
bnd = [(0, float("inf")),(0, float("inf")),(0, float("inf"))]
opt = linprog(c=obj, A_ub=lhs_ineq, b_ub=rhs_ineq, bounds=bnd,method="simplex")
-opt.fun.round(3)
opt.x.round(3)
(-1/opt.fun) * opt.x
(-1/opt.fun).round(3)

0.217

array([0.087, 0.13 , 0.   ])

array([0.4, 0.6, 0. ])

4.6